= Rose
:toc: left
:source-highlighter: highlightjs

== Basic Usage

[source,typescript]
----
include::../test/index.ts[tag=first-import,indent=0]
include::../test/index.ts[tag=first,indent=0]
----

== Core Concepts

- Code generated by introspecting an existing database's schema
- A metamodel for describing a table and its columns
- A Domain Specific Language (DSL) for building SQL queries
- Mapping rows to objects

=== Commands

Commands are the starting point for any query. Familiar ones are `select`, `update`, `delete` and `insert`.

Commands provide a fluent API for composing queries.

DDL commands are not supported.

=== Metamodel

The metamodel serves two purposes:

- Maps TypeScript identifiers to table and column names
- Provides a fluent API for comparing columns to expressions or values

=== Row Mapping

You can select "nested" objects. Parent/child relationships are worked out by hashing all of the parent's column values
together.

include::./QuickStart.adoc[]

include::./ConstructingAndExecutingAQuery.adoc[]

include::./Justification.adoc[]

include::./AlternateProjects.adoc[]
