= Commands

Commands are the outermost part of a single query. You can
https://www.postgresql.org/docs/current/sql-commands.html[refer to the list of the SQL commands supported by PostgreSQL].

You can normally distinguish "command" functions from other kinds of DSL functions, because they often allow chaining
methods, and provide a `finalise()` method, which converts xref:how-it-works.adoc[the intermediate AST] into a string.

_rose_ does not currently provide any Data Definition Language (DDL) commands. For many applications, you will want to
write your DDL queries directly in SQL, as they are often executed in database migrations, separate from your
application's main code.

The API docs can help you explore the available commands and DSL functions.

== `select()`

A `SELECT` query. Pass it a "xref:query-selectors.adoc[query selector]" object.

=== Chained methods

- `distinct()`: https://www.postgresql.org/docs/current/sql-select.html#SQL-DISTINCT[sets the "distinct" clause].
- `distinctOn()`: https://www.postgresql.org/docs/current/sql-select.html#SQL-DISTINCT[sets the "distinct on" clause].
- `from()`: explicitly https://www.postgresql.org/docs/current/sql-select.html#SQL-FROM[sets the "from" clause].
   Note that for some queries, it's optional to specify this:  _rose_ can infer the selected tables from the column
   metamodels.
- `groupBy()`: https://www.postgresql.org/docs/current/sql-select.html#SQL-GROUPBY[sets the "group by" clause].
- `limit()`: https://www.postgresql.org/docs/current/sql-select.html#SQL-LIMIT[sets the "limit" clause].
- `orderBy()`: https://www.postgresql.org/docs/current/sql-select.html#SQL-ORDERBY[sets the "order by" clause]. You can
  pass column metamodels by column their `asc()` or `desc()` methods, e.g. `select({...}).orderBy(QFilm.title.asc())`.
- `where()`: https://www.postgresql.org/docs/current/sql-select.html#SQL-WHERE[sets the "where" clause].
- `with()`: used for https://www.postgresql.org/docs/current/sql-select.html#SQL-WITH[common table expression queries].
   Sub-queries can be created using the `select()` DSL function, wrapped in `withCte()`.

=== From and Join DSL

When calling `from()`, you can join "from" items in a few ways.

The most straightforward way is to call one of the join methods from the table metamodel. E.g.
+
[source,typescript]
----
select(/* ... */).from(
  QFilm.$table
    .innerJoin(QFilmActor)
    .on(QFilmActor.filmId.eq(QFilm.filmId))
    .innerJoin(QActor)
    .on(QActor.actorId.eq(QFilmActor.actorId))
)
----

There are also DSL functions to help you construct "from" and "join" items.

- `from()` - converts and wraps elements (AST nodes, builder instances, or even just a string for the table name) for use as a "from" item.
- `join()` - a starting point for any other type of join. E.g. `join(QFilm).innerJoin(...)`
- `crossJoin()`
- `fullJoin()`
- `innerJoin()`
- `leftJoin()`
- `rightJoin()`

=== With queries / common table expressions

Wrap queries in `withCte()`

=== Other variations

- `selectExists()`: a convenience function for querying the existence of a result in a query
- `subSelect()`: builds a sub-query node
- `selectSubQuery()`: builds an aliased sub-query

== Transactions

=== `begin()`

Starts a transaction. You can set the transaction's isolation level, read mode, and deferrable flag.

==== Chained methods

- `isolationLevel()`: sets the isolation level
- `readMode()`: sets the read mode
- `deferrable()`: sets the deferrable flag
- `finalise()`: prepares the query so that it can be executed

=== `commit()`

Ends a transaction, committing it.

==== Chained methods

- `andChain()`: sets whether a new transaction is immediately started with the same characteristics.
- `finalise()`: prepares the query so that it can be executed

=== `rollback()`

Aborts a transction.

- `andChain()`: sets whether a new transaction is immediately started with the same characteristics.
- `finalise()`: prepares the query so that it can be executed
