= Connection Manager and Database Context

The AbstractConnectionManager and AbstractDatabaseContext are optional abstract classes that you may extend. In combination, they
provide the following features:

- Designed to work with connection pools.
- Automatically releases connections.
- Automatically handles committing or rolling back transactions.

You do not need to use these classes to make use of _rose_'s other features.

To make use of them:

- Extend `AbstractDatabaseContext`.
  - Add any properties that should be made available only when a database connection is available.
  - As an example, if you use the repository pattern to access entities, you could have a property `public readonly filmRepository = new FilmRepository(this.client)`.
- Extend `AbstractConnectionManager`
  - `createDatabaseContext()` should return an ew instance of your concrete `DatabaseContext` class.
  - `pool()` should initialise and/or return a singleton instance of your connection pool.
  - You may also want to add a `dispose()` method, for cleanly closing the connection pool.

== Example implementation

[source,typescript]
----
include::example$/test/connection-manager.ts[tag=example1,indent=0]
----
