= Query Selectors

When you call `select()`, you must pass a "query selector".This is an object, whose keys are the aliases of the
selected values.The values can be one of the following types.

== Column selector

You can pass a column metamodel as a selector. This is the simplest selector.

[source,typescript]
----
select({
    title: QFilm.title
});
----

== Expression selector

You can construct a SQL expression to use as a selector.

[source,typescript]
----
select({
    title: selectExpression(
        initcap(QFilm.title.col())
    )
});
----

In the above example, we do the following:

- Convert the column metamodel `QFilm.title` to a column reference node
- Pass the column reference node to the DSL function `initcap()`, which returns a function expression node.
- Pass the function expression node to `selectExpression()`

== Nested one selector

You can nest selected values into a single object. This is useful for converting a flat table into an object graph, or
for including data from joined tables.

[source,typescript]
----
select({
    film: selectNestedOne({
        title: QFilm.title
    })
});
----

== Nested many selector

You can nest multiple values as objects in an array. This could be used for joining across tables, perhaps when
grouping is desired.

[source,typescript]
----
select({
    id: QActor.actorId,
    films: selectNestedMany({
        title: QFilm.title
    })
});
----

The above example will return an array of objects, each containing an `id` and `films`, the latter containing an array
of objects containing `title`. (The rest of the query, to join and order the tables, has been left out.)

[WARNING]
====
_rose_ does not know the relationships between selected columns. To work out the "parent", rose will attempt to hash
all the other properties of the row object.

This is not foolproof - if your query has not selected enough unique columns from the "parent" table, you might find
data is grouped unexpectedly - and although a fast hashing algorithm is used, you may find it easier & faster to instead
perform a second query to retrieve nested data, and join it with the parent data within your application code.

Another option is to use PostgreSQL's JSON(B) functions to construct objects.
====

=== RowHasher

"Parent" objects are determined by hashing the non-nested properties together.

The default hashing function uses the MD5 algorithm. You can replace the hashing function with a faster implementation,
making use of a library like [metrohash](https://www.npmjs.com/package/metrohash) or
[xxhash](https://www.npmjs.com/package/xxhash-wasm).

Replace the default RowHasher function, by calling `setDefaultRowHasher()`.

Here's how to use xxhash-wasm:

```typescript
import * as xxhashModule from "xxhash-wasm";
import * as R from '@rosepg/rose';

const xxhashModule = await require("xxhash-wasm");

async function initialiseRose() {
    // The WASM module must be loaded asynchronously
    const xxhash = await xxhashModule();

    // At the time of writing, the types for xxhash-wasm were incorrect. You might need to use a type assertion like this.
    //const xxhash = await (xxhashModule as unknown as () => Promise<xxhashModule.XXHashAPI>)();

    const seed = BigInt(Date.now());

    // Define our RowHasher implementation
    function xxhashRowHasher<TDataClass>(
        row: TDataClass,
        propertiesToHash: string[]
    ) {
        const hash = xxhash.create64(seed);
        for (const key of propertiesToHash) {
            hash.update(`${key}=${(<any>row)[key]};`);
        }
        return hash.digest().toString(16);
    }

    R.setDefaultRowHasher(xxhashRowHasher);
}

// Elsewhere, in your app's startup code...
async function startApp() {
    await initialiseRose();
    // ...
}
```
